### PR TITLE
Feature: Add filter for ABs to stats table page

### PR DESCRIPTION
**Pull request by benjamin-t-brown**
- Added filter to stats page to filter by minimum number of at bats.  The filter changes the url so on the public url page you can copy the link and everybody will see what you see.
- Fixed some dom nesting errors I was seeing on the <table> in the scorer
- Moved helper text to top of stats table page and added "Click Me" text next to the help icon because of the feedback that nobody knew you could click that.

filter-by-ab

### CODE REVIEW

**Comment by laberle** [comment]
The idea is good, but a few things I would change:

1. "Moved helper text to top of stats table page and added "Click Me" text next to the help icon because of the feedback that nobody knew you could click that." I think the helper text should still be at the bottom of the stats table page, especially if you're adding more things (a filter) at the bottom. It's a secondary use case (primary is using the table), and it's weird to have stuff below and above. Click Here is fine, but then the info icon becomes redundant and should be removed. Maybe "<a>Click here</a> to learn more about a particular stat."
2. The "Enable filtering" checkbox is redundant (and looks bad, IMHO). Just make the "Apply Filter" a toggle button between "Apply Filter" and "Remove Filter".
3. The font size is too big on the filter text (both the heading and the input label) compared to the rest of the text in the stats table. It could also be separated somehow, maybe like how it is on the Player page with a green background rounded corner box. It would feel less tacked on.
4. nit: The message displayed when the filter removes everything should probably mention that there's not enough data after filters are applied (to hint that maybe they should change the filter, not that the team doesn't have data).
5. (less important for now) The filter could more easily be made generic in the future by reordering: XX [>= || <=] YYY stat. XX is the input text box. >= or <= are a dropdown (could also add < and > and = if desired later, or call it min and max still) with the default set so that you can do min number of at bats easily since that's the primary use case. In the future you could make YYY stat a dropdown based on any stat displayed in the table (could be a future feature). You could also then add the ability to do multiple filters at the same time, generically (e.g., at least 10 at bats but less than 2 ROE).

**Comment by laberle** [comment]
> > "Moved helper text to top of stats table page and added "Click Me" text next to the help icon because of the feedback that nobody knew you could click that." I think the helper text should still be at the bottom of the stats table page, especially if you're adding more things (a filter) at the bottom. It's a secondary use case (primary is using the table), and it's weird to have stuff below and above. Click Here is fine, but then the info icon becomes redundant and should be removed. Maybe "Click here to learn more about a particular stat."
> 
> I don't think it looks weird at all to have description text on top and bottom; Nobody reads the bottom text, ever; it's the reason why it's not obvious you can click stuff in it. I am attempting to solve the problem that a first-time user doesn't know how to do something on the table. The filter is not for a first time user, it's for an experienced one, and hence is placed at the bottom where nobody usually scrolls to.
> 
If it's at the top, you're also presenting the user with more information than they need, before they need it. You tell them about player names and stats and things you can do before they've even looked at the table. I wouldn't read the text at the top (like I would tap through a popup telling me about new features after an app upgrade - anything that gets in the way of me finding the info I'm looking for on the page gets ignored), and after the first time I look at the page it's just in the way. Should this page be optimized for first-time users? If I was wondering how something worked, I would go looking around, and I would find it either way. Another thing we could do, since the table needs to scroll horizontally anyway, is make a separate column that more obviously links to the spray chart.

> > The "Enable filtering" checkbox is redundant (and looks bad, IMHO). Just make the "Apply Filter" a toggle button between "Apply Filter" and "Remove Filter".
> 
> I think forcing the user to apply a filter with a button is more intuitive than using a checkbox to enact a default filter then modify it. There are two reasons for this:
> 
> 1. With a lot of stats this page can become unresponsive for a few seconds as it recalculates stuff.  Bad for user experience unless you prime a user with a button where they expect something to take some time.
> 2. Filters can be complex, so you likely want to set it up, then apply it, and wait for it to work, rather than for it to live update as you change.  I know there's just one field to edit now, but it could get frustrating for more: Since it's on the bottom, it changes position as the table above it changes size, so you may have frustration as a user modifies the filter, then it live updates, and the table changes size, which moves the filter options up/down.  I think you prime an  expectation of change by enforcing a button change with each change in the filter.
> 
I think there's some miscommunication here. I think you should *only* have a button; no checkbox. As it is, you have to click two things to get the filter to apply. The button would just change from Apply Filter to Remove Filter, and back, as it does already. If there's a performance issue or a repositioning issue, you could auto turn off the filter (change the button back to "Apply Filter") when the user edits a filter. 

> > The font size is too big on the filter text (both the heading and the input label) compared to the rest of the text in the stats table. It could also be separated somehow, maybe like how it is on the Player page with a green background rounded corner box. It would feel less tacked on.
> 
> Its the same font size and separation as on the "Game" tab, I was trying to keep it consistent.
> 
> image image
> 
Yeah that font size has always annoyed me :) I don't like it in either place. But I forget about it because it's not a page I go to often. I think now with the runners/outs/innings/scoring that Thomas has added there is an opportunity to improve that part of the "Game" tab (obviously not part of this).

> > The message displayed when the filter removes everything should probably mention that there's not enough data after filters are applied (to hint that maybe they should change the filter, not that the team doesn't have data).
> 
> I was attempting to make a message that applied to both the case where there was no data to work with and where the filter caused there to be no data to work with
> 
Sure, makes sense. You could still add a "maybe check to see if you have a filter applied" thing at the end.

> > (less important for now) The filter could more easily be made generic in the future by reordering: XX [>= || <=] YYY stat. XX is the input text box. >= or <= are a dropdown (could also add < and > and = if desired later, or call it min and max still) with the default set so that you can do min number of at bats easily since that's the primary use case. In the future you could make YYY stat a dropdown based on any stat displayed in the table (could be a future feature). You could also then add the ability to do multiple filters at the same time, generically (e.g., at least 10 at bats but less than 2 ROE).
> 
> I question whether you want this. More functionality does not necessarily mean a better product in this case, if it overcomplicates the reason for it in the first place. My story is: As a user, I want to filter out insignificant stats easily. My story is not: as a user I want to have the most customizable way to see the stats table.

Sure, but everyone has a different definition of "insignificant stats", or simple things they might want to filter on. There is a way to make the functionality easy to use but still powerful.

**Comment by benjamin-t-brown** [comment]
> I think there's some miscommunication here. I think you should only have a button; no checkbox. As it is, you have to click two things to get the filter to apply. The button would just change from Apply Filter to Remove Filter, and back, as it does already. If there's a performance issue or a repositioning issue, you could auto turn off the filter (change the button back to "Apply Filter") when the user edits a filter.
and 
> Everyone has a different definition of "insignificant stats", or simple things they might want to filter on. There is a way to make the functionality easy to use but still powerful.

We could just make a new page/modal that edits this filter, then some kind of banner or icon or something that indicates the list is filtered.  Click button to edit filter -> opens new page/modal -> edit filter -> save filter...  It's more extensible, but more weighty...

**Comment by benjamin-t-brown** [comment]
> Yeah that font size has always annoyed me :) I don't like it in either place. But I forget about it because it's not a page I go to often. I think now with the runners/outs/innings/scoring that Thomas has added there is an opportunity to improve that part of the "Game" tab (obviously not part of this).

It's just an h2, I've been using it for accessibility reasons since screen readers pick them out.  The actual table could use some light borders and I do like the idea of bolding the innings or whatever, but these aren't clickable so I think they should be differentiated from the game/lineup ones.

**Comment by benjamin-t-brown** [comment]
> Should this page be optimized for first-time users?

I think so... it's the public link page you send out, so most people clicking it will either be first time users or not familiar with it, at the very least.

> Another thing we could do, since the table needs to scroll horizontally anyway, is make a separate column that more obviously links to the spray chart.

It's workable to do that, but I don't like the idea of making users scroll right to see a really cool feature we have.

**Comment by benjamin-t-brown** [comment]
> If it's at the top, you're also presenting the user with more information than they need, before they need it. You tell them about player names and stats and things you can do before they've even looked at the table. I wouldn't read the text at the top (like I would tap through a popup telling me about new features after an app upgrade - anything that gets in the way of me finding the info I'm looking for on the page gets ignored), and after the first time I look at the page it's just in the way.

We are seeing this much differently.  It's like instructions for a test or filling out a form.  You would expect that to be at the top, not the bottom in case there was some kind of caveat or quirk that would make you need to fill it out in a certain way.  If they're at the bottom, then I have to go back and re-evaluate everything I'm seeing with new context.  If they are at the top, I am prepped to see that info already and don't have to do that which leads to less perceived cognitive load.

This isn't as much of a big deal if the page is simplified with the above suggestion of adding a Filter button, and moving all that into a different window, since the page itself gets simplified.

**Pull request closed without merging**
